apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: monitoring
      interval: 1m
  values:
    dashboards:
      default:
        node-exporter:
          url: https://grafana.com/api/dashboards/1860/revisions/32/download
  nodeSelector:
    kubernetes.io/arch: amd64
