apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-operator
      sourceRef:
        kind: HelmRepository
        name: grafana-operator
        namespace: monitoring
      interval: 1m