apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: chatgpt-telegram
  namespace: chatgpt-telegram
spec:
  imageRepositoryRef:
    name: loqutus/chatgpt-telegram
  policy:
    numerical:
      order: asc
